from dataclasses import dataclass

@dataclass
class DataIngestionOutput:
    file_store_path:str
    train_file_path:str
    test_file_path:str
class DataTransformationOutput:...
class DataValidationOutput:...
class ModelTrainingOutput:...
class ModelPusherOutput:...
class ModelEvaluationOutput:...